/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Admin;


import Principal.Tela_Inicial;
import Principal.Tela_Inicial;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoope
 */
public class AdministracaoGeral extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicial
     */
    
//     Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
//        int lar = (int) tela.getWidth();
//        int alt = (int) tela.getHeight();
        
    public AdministracaoGeral() {
        initComponents();
        setTitle("Distribuidora Ítalo");
        setSize(670, 580);
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Estoque = new javax.swing.JButton();
        Estoque1 = new javax.swing.JButton();
        Estoque2 = new javax.swing.JButton();
        Estoque3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton2.setText("Tela Inicial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 500, 120, 29);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Distribuidora Ítalo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 510, 126, 21);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Administração Geral");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 200, 29);

        Estoque.setBackground(new java.awt.Color(255, 255, 255));
        Estoque.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Estoque.setText("Alterar funcionário");
        Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(Estoque);
        Estoque.setBounds(430, 180, 170, 29);

        Estoque1.setBackground(new java.awt.Color(255, 255, 255));
        Estoque1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Estoque1.setText("Ver funcionários");
        Estoque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estoque1ActionPerformed(evt);
            }
        });
        getContentPane().add(Estoque1);
        Estoque1.setBounds(430, 220, 170, 29);

        Estoque2.setBackground(new java.awt.Color(255, 255, 255));
        Estoque2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Estoque2.setText("Deletar funcionário");
        Estoque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estoque2ActionPerformed(evt);
            }
        });
        getContentPane().add(Estoque2);
        Estoque2.setBounds(430, 260, 170, 29);

        Estoque3.setBackground(new java.awt.Color(255, 255, 255));
        Estoque3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Estoque3.setText("Cadastrar funcionário");
        Estoque3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estoque3ActionPerformed(evt);
            }
        });
        getContentPane().add(Estoque3);
        Estoque3.setBounds(430, 140, 170, 29);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bem-Vindo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 40, 200, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Tela_Inicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstoqueActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_EstoqueActionPerformed

    private void Estoque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estoque1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estoque1ActionPerformed

    private void Estoque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estoque2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estoque2ActionPerformed

    private void Estoque3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estoque3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estoque3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracaoGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracaoGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracaoGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracaoGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracaoGeral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Estoque;
    private javax.swing.JButton Estoque1;
    private javax.swing.JButton Estoque2;
    private javax.swing.JButton Estoque3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
