/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Admin;


import View.Escritório.*;
import Controller.Conexao;
import Controller.FuncionárioDAO;
import Controller.ProdutoDAO;
import Modelo.Funcionário;
import Modelo.Produto;
import Principal.Tela_Inicial;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author Hoope
 */
public class Alterar_Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicial
     */
    
//     Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
//        int lar = (int) tela.getWidth();
//        int alt = (int) tela.getHeight();
    int id;
        
    public Alterar_Funcionario(Funcionário f) {
        initComponents();
        setTitle("Distribuidora Ítalo");
        setSize(670, 580);
        setLocationRelativeTo(this);
        PegarValores(f);
        id = f.getId();
        
    }
    
    public void PegarValores(Funcionário p){
        Connection con = Conexao.AbrirConexao();
        FuncionárioDAO sql = new FuncionárioDAO(con);
        
        List<Funcionário> lista = new ArrayList<>();
        lista = sql.PreAlterar(p);
        
        int i = 0;
        for (Funcionário tab : lista) {
            //Object object = arr[j];
            
            JtfNome.setText(tab.getNome());
            JtfUsu.setText(tab.getUser());
            JtfSen.setText(tab.getSenha());
            JtfCpf.setText(tab.getCpf());
            JcbNivel.setSelectedIndex(tab.getNível());
            i++; 
        }
        Conexao.FecharConexao(con);
    }

    private Alterar_Funcionario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JtfCpf = new javax.swing.JFormattedTextField();
        JcbNivel = new javax.swing.JComboBox<>();
        JtfSen = new javax.swing.JPasswordField();
        JtfUsu = new javax.swing.JTextField();
        JtfNome = new javax.swing.JTextField();
        Alterar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton2.setText("Tela Inicial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 500, 120, 29);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alteração de Funcionários");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 250, 29);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuário:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 140, 140, 21);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nível:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 320, 50, 21);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nome:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 80, 50, 21);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Distribuidora Ítalo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 510, 126, 21);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Senha:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 200, 50, 21);

        try {
            JtfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(JtfCpf);
        JtfCpf.setBounds(300, 260, 200, 30);

        JcbNivel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        JcbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Escolha um nível)", "Nível 1", "Nível 2", "Nível 3" }));
        getContentPane().add(JcbNivel);
        JcbNivel.setBounds(300, 320, 200, 30);

        JtfSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfSenActionPerformed(evt);
            }
        });
        getContentPane().add(JtfSen);
        JtfSen.setBounds(300, 200, 200, 30);

        JtfUsu.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        JtfUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfUsuActionPerformed(evt);
            }
        });
        getContentPane().add(JtfUsu);
        JtfUsu.setBounds(300, 140, 200, 30);

        JtfNome.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        JtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(JtfNome);
        JtfNome.setBounds(300, 80, 200, 30);

        Alterar.setBackground(new java.awt.Color(0, 204, 0));
        Alterar.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        Alterar.setForeground(new java.awt.Color(255, 255, 255));
        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        getContentPane().add(Alterar);
        Alterar.setBounds(220, 390, 150, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 454, 120, 30);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CPF:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 260, 120, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Tela_Inicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void JtfUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfUsuActionPerformed

    
    
    
    
    
    
    
    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        // TODO add your handling code here:
       Connection con = Conexao.AbrirConexao();
       FuncionárioDAO sql = new FuncionárioDAO(con);
       Funcionário f = new Funcionário();
       
       int n = JcbNivel.getSelectedIndex();
        System.out.println(n+"");
        
        if(n != 0){
            f.setNome(JtfNome.getText());
            f.setUser(JtfUsu.getText());
            f.setSenha(JtfSen.getText());
            f.setCpf(JtfCpf.getText());
            f.setNível(JcbNivel.getSelectedIndex());
            
            JOptionPane.showMessageDialog(null, sql.Alterar(f,id),"Distribuidora Ítalo",JOptionPane.INFORMATION_MESSAGE);
            JtfNome.setText("");
            JtfUsu.setText("");
            JtfSen.setText("");
            JtfCpf.setText("");
            JcbNivel.setSelectedIndex(0);
            
            new AdministracaoGeral().setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Escolha um nível suportado","Distribuidora Ítalo",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_AlterarActionPerformed

    private void JtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AdministracaoGeral().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JtfSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfSenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfSenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alterar_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JComboBox<String> JcbNivel;
    private javax.swing.JFormattedTextField JtfCpf;
    private javax.swing.JTextField JtfNome;
    private javax.swing.JPasswordField JtfSen;
    private javax.swing.JTextField JtfUsu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
