/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Escritório;


import Controller.Conexao;
import Controller.ProdutoDAO;
import Modelo.Produto;
import Principal.Tela_Inicial;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Hoope
 */
public class Excluir_Pro extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicial
     */
    
//     Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
//        int lar = (int) tela.getWidth();
//        int alt = (int) tela.getHeight();
        
    public Excluir_Pro() {
        initComponents();
        setTitle("Distribuidora Ítalo");
        setSize(670, 580);
        setLocationRelativeTo(this);
        AtualizaTable();
    }
    
    public void AtualizaTable_Vencidos(){
        Connection con = Conexao.AbrirConexao();
        ProdutoDAO sql = new ProdutoDAO(con);
        
        List<Produto> lista = new ArrayList<>();
        lista = sql.Consulta_Data();
        Date d = new Date();
        SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");

        String[] data_hj = data.format(d).split("/");
        int i = 0;
        
        for (Produto tab : lista) {
            
            String[] data_venc = tab.getData().split("/");
            Produto p = new Produto();
            if(Integer.parseInt(data_hj[2]) > Integer.parseInt(data_venc[2])){
                   //JOptionPane.showMessageDialog(null, tab.getId());
              //id[i] = tab.getId();
                
                p.setId(tab.getId());
                //id[i] = p.getId()+"";
                System.out.println("Id "+i+": "+p.getId());
                JOptionPane.showMessageDialog(null,"Produto de Id("+p.getId()+") está vencido","Distribuidora Ítalo",JOptionPane.INFORMATION_MESSAGE);
                
                i++;
            }else{
                if(Integer.parseInt(data_hj[1]) > Integer.parseInt(data_venc[1]) && Integer.parseInt(data_hj[2]) > Integer.parseInt(data_venc[2])){
                 p.setId(tab.getId());
                //id[i] = p.getId()+"";
                System.out.println("Id "+i+": "+p.getId());
                JOptionPane.showMessageDialog(null,"Produto de Id("+p.getId()+") está vencido","Distribuidora Ítalo",JOptionPane.INFORMATION_MESSAGE);
                i++;
                }else{
                    if(Integer.parseInt(data_hj[0]) > Integer.parseInt(data_venc[0]) && Integer.parseInt(data_hj[1]) > Integer.parseInt(data_venc[1]) && Integer.parseInt(data_hj[2]) > Integer.parseInt(data_venc[2])){
                      p.setId(tab.getId());
                      //id[i] = p.getId()+"";
                      System.out.println("Id "+i+": "+p.getId());
                      JOptionPane.showMessageDialog(null,"Produto de Id("+p.getId()+") está vencido","Distribuidora Ítalo",JOptionPane.INFORMATION_MESSAGE);
                      i++;
                    }else{
                       
                    }
                }
            }
            
            
            
        }
        Conexao.FecharConexao(con);
        
    }
    
    
    public void AtualizaTable(){
        Connection con = Conexao.AbrirConexao();
        ProdutoDAO sql = new ProdutoDAO(con);
        
        List<Produto> lista = new ArrayList<>();
        lista = sql.Consulta();
        DefaultTableModel tbm = (DefaultTableModel) jTable2.getModel();
        while(tbm.getRowCount() > 0){
            tbm.removeRow(0);
        }
        int i = 0;
        for (Produto tab : lista) {
            //Object object = arr[j];
            tbm.addRow(new String[1]);
            jTable2.setValueAt(tab.getId(), i, 0);
            jTable2.setValueAt(tab.getTipo(), i, 1);
            jTable2.setValueAt(tab.getMarca(), i, 2);
            jTable2.setValueAt(tab.getCaixas(),i,3);
            jTable2.setValueAt(tab.getPreco(),i,4);
            jTable2.setValueAt(tab.getData(),i,5);
            i++; 
        }
        Conexao.FecharConexao(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BtnVencidos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton2.setText("Tela Inicial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 500, 120, 29);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Excluir produto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 220, 29);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Distribuidora Ítalo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 510, 126, 21);

        jTable2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipo", "Marca", "Caixas", "Preço", "Data de Validade"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 70, 600, 360);

        BtnVencidos.setBackground(new java.awt.Color(204, 255, 0));
        BtnVencidos.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        BtnVencidos.setText("Ver produtos  vencidos");
        BtnVencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVencidosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVencidos);
        BtnVencidos.setBounds(320, 20, 200, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 454, 120, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Tela_Inicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Controle_Escritório().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int linha = jTable2.getSelectedRow();
        int id = (int) jTable2.getValueAt(linha, 0);
        
        Produto a = new Produto();
        a.setId(id);
        
        int confirm = JOptionPane.showConfirmDialog(null,"Deseja mesmo excluir o produto de Código ("+a.getId()+")","Distribuidora",JOptionPane.INFORMATION_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
            Connection con = Conexao.AbrirConexao();
            ProdutoDAO sql = new ProdutoDAO(con);
            JOptionPane.showMessageDialog(null, sql.Deletar(a),"Distribuidora",JOptionPane.INFORMATION_MESSAGE);
            new Controle_Escritório().setVisible(true);
            dispose();
            
        }else{
            
        }
        
        //new Controle_Escritório().setVisible(true);

        
        // AtualizaTable();

    }//GEN-LAST:event_jTable2MouseClicked

    private void BtnVencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVencidosActionPerformed
        // TODO add your handling code here:
        AtualizaTable_Vencidos();
        //  JOptionPane.showMessageDialog(null,r);
    }//GEN-LAST:event_BtnVencidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Excluir_Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Excluir_Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Excluir_Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Excluir_Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Excluir_Pro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVencidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
